services:
  bot:
    container_name: book-helper-bot
    build:
      context: .
    image: book-helper-bot:latest
    env_file:
      - .env
    command: ["poetry", "run", "watchmedo", "auto-restart", "--recursive", "--", "python", "main.py"]
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy


  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
