[tool.poetry]
name = "book-bot"
version = "0.1.0"
description = ""
authors = ["vitayushchyk <vitay2715@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
python-telegram-bot = "^21.11.1"
beautifulsoup4 = "^4.13.3"
pydantic-settings = "^2.8.1"
pydantic = "^2.10.6"
selenium = ">=4.0.0"
webdriver-manager = "^4.0.2"
httpx = "^0.28.1"
redis = "^5.2.1"
asyncio-redis = "^0.16.0"
asyncio = "^3.4.3"
aiohttp = "^3.11.18"
colorlog = "^6.9.0"
sqlmodel = "^0.0.24"
alembic = "^1.15.2"
psycopg2-binary = "^2.9.10"
asyncpg = "^0.30.0"
watchdog = "^6.0.0"
sqlalchemy = "^2.0.41"


[tool.poetry.group.dev.dependencies]
isort = "^6.0.1"
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
