[tool.poetry]
name = "hippo-book-bot"
version = "0.1.0"
description = ""
authors = ["vitayushchyk <vitay2715@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"
uvicorn = "^0.35.0"
fastapi = "^0.116.1"
python-telegram-bot = "^22.3"
colorlog = "^6.9.0"
pydantic-settings = "^2.10.1"
beautifulsoup4 = "^4.13.4"
aiohttp = "^3.12.15"
redis = "^6.2.0"
sqlalchemy = "^2.0.41"
sqlmodel = "^0.0.24"
asyncpg = "^0.30.0"
alembic = "^1.16.4"
requests = "^2.32.4"
pydantic = "^2.11.7"
asyncio-redis = "^0.16.0"
asyncio = "^3.4.3"
psycopg2-binary = "^2.9.10"
watchdog = "^6.0.0"


[tool.poetry.group.dev.dependencies]
isort = "^6.0.1"
black = "^25.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
