name: Deploy to AWS

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t book-bot -f Dockerfile .

      - name: Tag Docker image
        run: docker tag book-bot:latest ${{ secrets.ECR_URI }}/book-bot:latest

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ secrets.ECR_URI }}/book-bot:latest
